parser: babel-eslint
extends: airbnb
rules:
  semi:
    - 2
    - never
  indent:
    - 2
    - tab
  react/prop-types: off
  react/jsx-indent:
    - 2
    - tab
  react/jsx-indent-props:
    - 2
    - tab
  no-tabs: off
